#NOTE: Autogenerated documentation to help learn the proper formatting for Ruby.

# Determines if a number is prime.
#
# @param value [Integer] The number to check for primality.
# @return [Boolean] Returns true if the number is prime, otherwise false.
def is_prime(value)
  i = 2
  while i <= (value+1)/2 do
    return false if value % i == 0
    i += 1
  end
  return true
end

# Calculates the derived number.
#
# @param value [Integer] The number to process.
# @param m [Integer] The starting divisor (default: 2).
# @return [Integer] The result of the derivative calculation.
def derivative(value ,m)
  if is_prime(value) == false
    while value % m != 0 do
      m += 1
    end
    n = value / m
    return n + m * derivative(n, 2)
  end
  return 1
end

# Print derived number.
puts derivative(gets.to_i,2)
